# Generated by Django 4.1.6 on 2023-02-15 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_directionurl_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionurl',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
