# Generated by Django 4.1.6 on 2023-02-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_directionurl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
