name: API Checks

on:
  push:
jobs:
  test-api:
    name: Test and Lint API
    runs-on: ubuntu-latest
    steps:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Test API
        run: docker-compose build && docker-compose run --rm web sh -c "python manage.py test"

      - name: Lint API
        run: docker-compose build && docker-compose run --rm web  sh -c "flake8"
